#!/usr/bin/env bash
# ============================================================================
# SHARED DEPLOYMENT PREREQUISITES — secrets, the network, and the LEDGERS.
#
#   bash deploy/shared.sh                       # no real chain (all simulated)
#   bash deploy/shared.sh --chain=besu          # local 5-node QBFT
#   bash deploy/shared.sh --chain=mst           # public MST testnet
#   bash deploy/shared.sh --chain=besu,mst      # both
#   bash deploy/shared.sh --chain=fabric        # see the FABRIC note below
#
# SOURCE IT, don't run it, when you need the chain variables afterwards —
# `deploy/identity.sh` and `deploy/tokenization.sh` do exactly that, because a
# subprocess cannot export BESU_RPC_URL back to its caller.
#
# ── THE THREE LEDGERS, HONESTLY ─────────────────────────────────────────────
#   besu    REAL. Vendored 5-node QBFT network, chainId 1337. Started here.
#   mst     REAL. Public testnet, chainId 91562037. Remote — nothing to start,
#           but MST_RPC_URL + MST_OPERATOR_KEY must be in the git-ignored .env.
#   fabric  SIMULATED IN CONTAINERS, and that is not a shortcut: neither split
#           compose file passes FABRIC_* through, and the connection profile
#           `make fabric-up` emits binds host localhost ports with
#           `asLocalhost: true`, which a container cannot reach. Real Fabric
#           therefore needs the HOST API — `make fabric-up && ./scripts/api-fabric.sh`.
#           Selecting it here is legitimate and gives you the fabric chain; it
#           just runs simulated, and this script says so rather than implying
#           an on-chain guarantee it cannot keep.
#
# EVM ONLY FOR IDENTITY. The DID and VC registries are Solidity contracts and
# `CredentialAnchor` exists solely on the EVM adapter, so identity can anchor on
# besu or mst and never on fabric. `deploy/identity.sh` enforces that.
# ============================================================================
set -euo pipefail
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

ENV_FILE="${ENV_FILE:-.env.personas}"
NETWORK="${NETWORK:-xi-net}"
BESU_RPC_PORT="${BESU_RPC_PORT:-8545}"

C="\033[1;36m"; Y="\033[1;33m"; R="\033[1;31m"; N="\033[0m"
say() { echo -e "${C}[shared]${N} $*"; }
warn() { echo -e "${Y}[shared] NOTE:${N} $*"; }
die() { echo -e "${R}[shared] ERROR:${N} $*" >&2; exit 1; }

# ── Chain selection ──────────────────────────────────────────────────────────
CHAINS=""
for a in "$@"; do
  case "$a" in
    --chain=*) CHAINS="${CHAINS},${a#--chain=}" ;;
    --besu)    CHAINS="${CHAINS},besu" ;;   # kept: the old flag still works
  esac
done
CHAINS="$(echo "${CHAINS#,}" | tr ',' ' ' | tr -s ' ')"
for c in $CHAINS; do
  case "$c" in
    besu|mst|fabric) ;;
    *) die "unknown chain '$c' — expected besu, mst or fabric (comma-separate to pick several)" ;;
  esac
done
export SHARED_CHAINS="$CHAINS"

command -v docker >/dev/null || die "docker is not on PATH"
command -v openssl >/dev/null || die "openssl is not on PATH"

# ── 1. Secrets ───────────────────────────────────────────────────────────────
# APPEND-ONLY, NEVER REGENERATED. Every custodial DID seed is encrypted under
# DID_MASTER_KEY; a new one orphans every organization that already exists —
# they survive and silently lose the ability to sign, surfacing much later as
# "Unsupported state or unable to authenticate data" on an unrelated onboarding.
[ -f "$ENV_FILE" ] || { say "minting $ENV_FILE (first run)"; echo "# Generated by deploy/shared.sh — git-ignored. KEEP THIS FILE." > "$ENV_FILE"; }
for key in JWT_SECRET DID_MASTER_KEY; do
  if grep -q "^${key}=.." "$ENV_FILE"; then say "$key present ✓"
  else say "$key missing — appending a generated one"; echo "${key}=$(openssl rand -hex 32)" >> "$ENV_FILE"; fi
done
# Repo .env FIRST (ledger settings), the deployment's own file LAST so its
# secrets win. Backwards, and every custodial seed becomes undecryptable.
if [ -f .env ]; then set -a; . ./.env; set +a; fi
set -a; . "./$ENV_FILE"; set +a

# ── 2. The shared network ────────────────────────────────────────────────────
docker network inspect "$NETWORK" >/dev/null 2>&1 || {
  say "creating the shared network '$NETWORK'"; docker network create "$NETWORK" >/dev/null; }
say "network '$NETWORK' ready ✓"

# ── 3. The ledgers ───────────────────────────────────────────────────────────
[ -n "$CHAINS" ] || warn "no --chain given: every ledger will be SIMULATED, and identity will have no registry to anchor on"

for chain in $CHAINS; do
case "$chain" in

  besu)
    say "besu — starting the vendored 5-node QBFT network…"
    docker compose -f docker-compose.besu-nodes.yml up -d >/dev/null

    # LIVENESS, NOT ROSTER. `qbft_getValidatorsByBlockNumber` returns the
    # CONFIGURED validator set — it answers "5" from a chain that has not
    # produced a block in days, which is how a stalled network was reported
    # ready while every transaction sat unmined. Ask whether the height MOVES.
    height() {
      curl -s -m 4 -X POST "http://localhost:${BESU_RPC_PORT}" -H 'Content-Type: application/json' \
        -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' 2>/dev/null \
        | sed -n 's/.*"result":"\([^"]*\)".*/\1/p'
    }
    say "besu — waiting for BLOCK PRODUCTION (not just a validator count)…"
    first=""; ok=0; h=""
    for i in $(seq 1 60); do
      h=$(height)
      if [ -n "$h" ]; then
        if [ -z "$first" ]; then first="$h"; elif [ "$h" != "$first" ]; then ok=1; break; fi
      fi
      sleep 2
    done
    [ "$ok" = 1 ] || die "besu is reachable but NOT producing blocks (height stuck at ${first:-unknown}).
  QBFT needs 4 of 5 validators; check 'docker logs besu-node1 | grep RoundChange'.
  A network that has lost consensus is not repaired by a restart — it needs
  'docker compose -f docker-compose.besu-nodes.yml down -v' to re-genesis, which
  DESTROYS all chain history and is deliberately left to a human."
    say "besu — producing blocks ✓ ($first → $h)"

    # THE NODES LIVE ON THEIR OWN NETWORK. Without this the split stacks cannot
    # reach them at all: besu-node1 is on 'besu-network', the APIs are on
    # 'xi-net', and the chain is simply ABSENT — which the app reports honestly
    # but which looks like a configuration mystery from the outside. Idempotent.
    if ! docker inspect besu-node1 --format '{{range $k,$v := .NetworkSettings.Networks}}{{$k}} {{end}}' | grep -q "$NETWORK"; then
      say "besu — attaching besu-node1 to '$NETWORK' so containerised stacks can reach it"
      docker network connect "$NETWORK" besu-node1
    fi
    export BESU_RPC_URL="${BESU_RPC_URL:-http://besu-node1:8545}"
    # The vendored QBFT dev operator, already committed in docker-compose.besu.yml.
    # A well-known test key for a local chain — NEVER a production credential.
    export BESU_OPERATOR_KEY="${BESU_OPERATOR_KEY:-0x8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63}"
    ;;

  mst)
    # REMOTE — nothing to start, everything to verify. The credentials live only
    # in the git-ignored .env; this script never writes or echoes them.
    [ -n "${MST_RPC_URL:-}" ] && [ -n "${MST_OPERATOR_KEY:-}" ] || die "mst needs MST_RPC_URL and MST_OPERATOR_KEY in .env (both, or neither — half a pair boots and then fails on the first mint).
  Testnet faucet: https://faucet.mstblockchain.com/"
    say "mst — probing $MST_RPC_URL…"
    cid=$(curl -s -m 10 -X POST "$MST_RPC_URL" -H 'Content-Type: application/json' \
      -d '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}' 2>/dev/null \
      | sed -n 's/.*"result":"\([^"]*\)".*/\1/p')
    [ -n "$cid" ] || die "mst did not answer eth_chainId at $MST_RPC_URL (network down, or the URL is wrong)"
    dec=$((cid))
    # The expected id is declared in config/chains.json. A mismatch means the URL
    # points at a DIFFERENT chain — the one failure that would otherwise mint
    # real assets somewhere nobody intended.
    [ "$dec" = "91562037" ] || die "mst answered chainId $dec, expected 91562037 — MST_RPC_URL points at the wrong network"
    say "mst — reachable ✓ (chainId $dec)"
    ;;

  fabric)
    if [ -f infra/fabric/.runtime/connection-org1.json ]; then
      warn "a REAL Fabric network is running, but a containerised stack cannot use it:
  the connection profile binds host localhost ports (asLocalhost: true), and neither
  split compose file passes FABRIC_* through. Fabric will run SIMULATED here.
  For real Fabric run the API on the host instead:  ./scripts/api-fabric.sh"
    else
      warn "fabric will run SIMULATED (no infra/fabric/.runtime — 'make fabric-up' creates it).
  Even then it is host-only; see the header of this script."
    fi
    say "fabric — selected (simulated) ✓"
    ;;
esac
done

# CHAIN_STRICT: refuse to boot when a REQUIRED chain is absent. besu is
# `required: true` in config/chains.json, so a deployment that asked for it
# should fail loudly rather than serve a platform whose mints silently vanish.
case " $CHAINS " in *" besu "*) export CHAIN_STRICT="${CHAIN_STRICT:-1}" ;; *) export CHAIN_STRICT="${CHAIN_STRICT:-0}" ;; esac

say "shared prerequisites ready.${CHAINS:+ chains: $CHAINS}"
