#!/usr/bin/env bash
# ============================================================================
# SHARED DEPLOYMENT PREREQUISITES — what BOTH products need, whatever the
# topology. Run it directly, or source it from a per-product script.
#
#   bash deploy/shared.sh              # secrets + network
#   bash deploy/shared.sh --besu       # …and the 5-node Besu QBFT chain
#
# The split mirrors `src/`: `shared` is not a shrug, it is the set of things
# neither product owns alone. Secrets are shared because a custodial DID seed
# written by identity must decrypt in tokenization. The docker network is
# shared because the identity seam crosses it. Besu is shared because both
# products anchor on it — identity writes DIDs and VCs, tokenization mints.
# ============================================================================
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

ENV_FILE="${ENV_FILE:-.env.personas}"
NETWORK="${NETWORK:-xi-net}"
BESU_RPC_PORT="${BESU_RPC_PORT:-8545}"
WANT_BESU=0
for a in "$@"; do [ "$a" = "--besu" ] && WANT_BESU=1; done

C="\033[1;36m"; R="\033[1;31m"; N="\033[0m"
say() { echo -e "${C}[shared]${N} $*"; }
die() { echo -e "${R}[shared] ERROR:${N} $*" >&2; exit 1; }

command -v docker >/dev/null || die "docker is not on PATH"
command -v openssl >/dev/null || die "openssl is not on PATH"

# ── 1. Secrets ───────────────────────────────────────────────────────────────
# APPEND-ONLY, NEVER REGENERATED. Every custodial DID seed is encrypted under
# DID_MASTER_KEY; minting a new one orphans every organization that already
# exists — they survive in the database and can no longer sign anything. The
# symptom arrives much later and names the wrong thing: "Unsupported state or
# unable to authenticate data" on an unrelated onboarding.
[ -f "$ENV_FILE" ] || { say "minting $ENV_FILE (first run)"; echo "# Generated by deploy/shared.sh — git-ignored. KEEP THIS FILE." > "$ENV_FILE"; }
for key in JWT_SECRET DID_MASTER_KEY; do
  if grep -q "^${key}=.." "$ENV_FILE"; then
    say "$key present ✓"
  else
    say "$key missing — appending a generated one"
    echo "${key}=$(openssl rand -hex 32)" >> "$ENV_FILE"
  fi
done

# Repo .env FIRST (ledger settings), the deployment's own file LAST so its
# secrets win. Backwards, and every custodial seed becomes undecryptable.
if [ -f .env ]; then set -a; . ./.env; set +a; fi
set -a; . "./$ENV_FILE"; set +a

# ── 2. The shared network ────────────────────────────────────────────────────
docker network inspect "$NETWORK" >/dev/null 2>&1 || {
  say "creating the shared network '$NETWORK'"
  docker network create "$NETWORK" >/dev/null
}
say "network '$NETWORK' ready ✓"

# ── 3. Besu, on request ──────────────────────────────────────────────────────
if [ "$WANT_BESU" = 1 ]; then
  say "starting the 5-node Besu QBFT network…"
  docker compose -f docker-compose.besu-nodes.yml up -d >/dev/null

  # LIVENESS, NOT ROSTER. `qbft_getValidatorsByBlockNumber` returns the
  # CONFIGURED validator set — it answers 5 from a chain that has not produced
  # a block in days, which is exactly how a stalled network was reported ready
  # while every transaction sat unmined in the pool. The only honest question
  # is whether the height MOVES, so ask twice and compare.
  height() {
    curl -s -m 4 -X POST "http://localhost:${BESU_RPC_PORT}" -H 'Content-Type: application/json' \
      -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' 2>/dev/null \
      | sed -n 's/.*"result":"\([^"]*\)".*/\1/p'
  }
  say "waiting for BLOCK PRODUCTION (not just a validator count)…"
  first=""; ok=0
  for i in $(seq 1 60); do
    h=$(height)
    if [ -n "$h" ]; then
      if [ -z "$first" ]; then first="$h"
      elif [ "$h" != "$first" ]; then ok=1; break
      fi
    fi
    sleep 2
  done
  [ "$ok" = 1 ] || die "Besu is reachable but NOT producing blocks (height stuck at ${first:-unknown}).
  QBFT needs 4 of 5 validators; check 'docker logs besu-node1 | grep RoundChange'.
  A network that has lost consensus cannot be repaired by a restart — it needs
  'docker compose -f docker-compose.besu-nodes.yml down -v' to re-genesis, which
  DESTROYS all chain history and is deliberately left to a human."
  say "Besu is producing blocks ✓ (height $first → $h)"
fi

say "shared prerequisites ready."
