/**
 * Custodial key management. The platform holds each DID's 32-byte Ed25519 seed
 * encrypted at rest (AES-256-GCM under DID_MASTER_KEY) and reconstructs the
 * keypair on demand via `didKeyFromSeed` — no KeyObject is ever serialized.
 * The org's key signs OrganizationMembership VCs on its behalf.
 */
import { createCipheriv, createDecipheriv, randomBytes } from "node:crypto";
import { didKeyFromSeed, issueCredential, signJwt, type DidKey } from "@tokenlayer/core";

const IV_LEN = 12; // AES-GCM standard nonce length
const TAG_LEN = 16;
const MEMBERSHIP_TTL_SECONDS = 365 * 24 * 3600;

export interface MembershipInput {
  orgEncSeed: string;
  orgDid: string;
  userDid: string;
  /** { organization, orgId, role, memberSince } — merged into credentialSubject. */
  claims: Record<string, unknown>;
  /** Unix seconds. */
  now: number;
}

/**
 * OUR OWN status type — deliberately NOT StatusList2021, which this is not.
 * Semantics: resolve this URL over HTTP. The answer is backed by an on-chain
 * registry when one is configured and by the database otherwise; the response's
 * `source` field says which. The type string is intentionally unchanged now that
 * the endpoint is chain-backed: the VC-facing contract ("resolve this URL") never
 * changed, and minting a second name for identical semantics would force every
 * verifier to handle both.
 */
export const REVOCATION_STATUS_TYPE = "SimpleRevocationStatus2024";

export interface OrgCredentialInput {
  orgEncSeed: string;
  orgDid: string;
  subjectDid: string;
  type: string;
  claims: Record<string, unknown>;
  /** Generated by the caller BEFORE signing: the VC embeds it in jti + credentialStatus. */
  credentialId: string;
  statusUrl: string;
  validityDays: number;
  /** Unix seconds. */
  now: number;
}

export interface Keystore {
  newSeed(): Buffer;
  encryptSeed(seed: Buffer): string;
  decryptSeed(enc: string): Buffer;
  keyOf(enc: string): DidKey;
  issueOrgCredential(input: OrgCredentialInput): { vcJwt: string; expiresAt: number };
  issueMembershipCredential(input: MembershipInput): { vcJwt: string; expiresAt: number };
}

/** Build a keystore bound to a 32-byte master key (hex, 64 chars). */
export function createKeystore(masterKeyHex: string): Keystore {
  const key = Buffer.from(masterKeyHex, "hex");
  if (key.length !== 32) throw new Error("DID master key must be 32 bytes (64 hex chars)");

  const newSeed = (): Buffer => randomBytes(32);

  const encryptSeed = (seed: Buffer): string => {
    const iv = randomBytes(IV_LEN);
    const cipher = createCipheriv("aes-256-gcm", key, iv);
    const ct = Buffer.concat([cipher.update(seed), cipher.final()]);
    return Buffer.concat([iv, cipher.getAuthTag(), ct]).toString("base64");
  };

  const decryptSeed = (enc: string): Buffer => {
    const buf = Buffer.from(enc, "base64");
    const iv = buf.subarray(0, IV_LEN);
    const tag = buf.subarray(IV_LEN, IV_LEN + TAG_LEN);
    const ct = buf.subarray(IV_LEN + TAG_LEN);
    const decipher = createDecipheriv("aes-256-gcm", key, iv);
    decipher.setAuthTag(tag);
    return Buffer.concat([decipher.update(ct), decipher.final()]);
  };

  const keyOf = (enc: string): DidKey => didKeyFromSeed(decryptSeed(enc));

  const issueOrgCredential = ({ orgEncSeed, orgDid, subjectDid, type, claims, credentialId, statusUrl, validityDays, now }: OrgCredentialInput): { vcJwt: string; expiresAt: number } => {
    const orgKey = keyOf(orgEncSeed);
    const expiresAt = now + validityDays * 24 * 3600;
    const vcJwt = signJwt(
      { alg: "EdDSA", typ: "JWT", kid: `${orgDid}#0` },
      {
        iss: orgDid, sub: subjectDid, jti: credentialId, iat: now, nbf: now, exp: expiresAt,
        vc: {
          "@context": ["https://www.w3.org/2018/credentials/v1"],
          type: ["VerifiableCredential", type],
          credentialSubject: { id: subjectDid, ...claims },
          credentialStatus: { id: statusUrl, type: REVOCATION_STATUS_TYPE },
        },
      },
      orgKey.privateKey,
    );
    return { vcJwt, expiresAt };
  };

  const issueMembershipCredential = ({ orgEncSeed, orgDid, userDid, claims, now }: MembershipInput): { vcJwt: string; expiresAt: number } => {
    const orgKey = keyOf(orgEncSeed);
    const expiresAt = now + MEMBERSHIP_TTL_SECONDS;
    const vcJwt = issueCredential({
      issuerDid: orgDid, issuerKey: orgKey.privateKey, subjectDid: userDid,
      claims, expiresAt, now, type: ["VerifiableCredential", "OrganizationMembership"],
    });
    return { vcJwt, expiresAt };
  };

  return { newSeed, encryptSeed, decryptSeed, keyOf, issueOrgCredential, issueMembershipCredential };
}
