#!/usr/bin/env bash
# Bring up the six-audience topology: two APIs, six persona edges, six web apps.
#
#   bash scripts/personas-up.sh
#
# WHY A SCRIPT AND NOT `docker compose up`. The tokenization API refuses to boot
# without IDENTITY_SERVICE_KEY, and that key can only be minted from a RUNNING
# identity deployment. So the order is fixed: identity first, mint, then
# tokenization. Compose cannot express "start A, ask A for a secret, give it to
# B" — pretending it could is how the split topology used to fail halfway with
# an error about an unset variable.
set -euo pipefail
cd "$(dirname "$0")/.."

C="\033[1;36m"; G="\033[1;32m"; Y="\033[1;33m"; R="\033[1;31m"; N="\033[0m"
say() { echo -e "${C}[personas]${N} $*"; }
die() { echo -e "${R}[personas] ERROR:${N} $*" >&2; exit 1; }

COMPOSE="docker compose -f docker-compose.personas.yml"
ENV_FILE=".env.personas"

command -v docker >/dev/null || die "docker is not on PATH"

# ── 1. Secrets that must exist before anything starts ────────────────────────
# Generated once and kept, because regenerating DID_MASTER_KEY would orphan every
# custodial seed already encrypted under the old one — the credentials would
# still be in the database and no longer decryptable.
if [ ! -f "$ENV_FILE" ]; then
  say "minting $ENV_FILE (first run)"
  {
    echo "# Generated by scripts/personas-up.sh — git-ignored, keep it."
    echo "JWT_SECRET=$(openssl rand -hex 32)"
    echo "DID_MASTER_KEY=$(openssl rand -hex 32)"
  } > "$ENV_FILE"
else
  say "reusing $ENV_FILE"
fi
set -a; . "./$ENV_FILE"; set +a
# Ledger settings, if the operator has any, come from the repo .env.
if [ -f .env ]; then set -a; . ./.env; set +a; fi

# ── 2. Identity first: its API, its three edges, its three apps ──────────────
say "building and starting the identity side…"
$COMPOSE up -d --build identity-api identity-issuer-edge identity-verifier-edge identity-holder-edge

ISSUER_PORT="${IDENTITY_ISSUER_API_PORT:-4110}"
say "waiting for the issuer edge on :$ISSUER_PORT…"
for i in $(seq 1 90); do
  if curl -sf "http://localhost:${ISSUER_PORT}/healthz" >/dev/null 2>&1 &&
     curl -so /dev/null -w '%{http_code}' "http://localhost:${ISSUER_PORT}/api/v1/config" | grep -qE '^(200|401)$'; then
    say "identity is up behind its edge ✓"; break
  fi
  [ "$i" = 90 ] && die "identity did not come up — try: $COMPOSE logs identity-api"
  sleep 2
done

# ── 3. The one credential binding the two products ───────────────────────────
# Minted THROUGH the issuer edge, not against the API directly, which is a small
# proof in itself: the edge really does proxy /orgs/:id/api-keys, and there is no
# back door needed to set the deployment up.
if grep -q '^IDENTITY_SERVICE_KEY=' "$ENV_FILE" 2>/dev/null; then
  say "peer key already present in $ENV_FILE"
else
  say "minting the identity:assert peer key through the issuer edge…"
  KEY=$(IDENTITY_URL="http://localhost:${ISSUER_PORT}/api/v1" node scripts/mint-identity-peer-key.mjs) \
    || die "could not mint the peer key"
  [ -n "$KEY" ] || die "the peer key came back empty"
  echo "IDENTITY_SERVICE_KEY=$KEY" >> "$ENV_FILE"
  say "peer key stored in $ENV_FILE (it is shown exactly once and never again)"
fi
set -a; . "./$ENV_FILE"; set +a

# ── 4. Everything else ───────────────────────────────────────────────────────
say "building and starting tokenization and all six web apps…"
$COMPOSE up -d --build

say "waiting for the tokenization edges…"
for port in "${TOKENIZATION_ISSUER_API_PORT:-4120}" "${TOKENIZATION_MARKETPLACE_API_PORT:-4121}" "${TOKENIZATION_ADMIN_API_PORT:-4122}"; do
  for i in $(seq 1 90); do
    curl -sf "http://localhost:${port}/healthz" >/dev/null 2>&1 && break
    [ "$i" = 90 ] && die "edge on :$port did not come up — try: $COMPOSE logs"
    sleep 2
  done
done

echo
echo -e "${G}✅ SIX AUDIENCE APPS ARE UP${N}"
echo
printf "  %-26s %-34s %s\n" "APP" "WEB" "ITS API EDGE"
printf "  %-26s %-34s %s\n" "───" "───" "────────────"
printf "  %-26s %-34s %s\n" "Identity · Issuer"      "http://localhost:${IDENTITY_ISSUER_WEB_PORT:-8090}"        "http://localhost:${ISSUER_PORT}"
printf "  %-26s %-34s %s\n" "Identity · Verifier"    "http://localhost:${IDENTITY_VERIFIER_WEB_PORT:-8091}"      "http://localhost:${IDENTITY_VERIFIER_API_PORT:-4111}"
printf "  %-26s %-34s %s\n" "Identity · Wallet"      "http://localhost:${IDENTITY_HOLDER_WEB_PORT:-8092}"        "http://localhost:${IDENTITY_HOLDER_API_PORT:-4112}"
printf "  %-26s %-34s %s\n" "Tokenization · Issuer"  "http://localhost:${TOKENIZATION_ISSUER_WEB_PORT:-8100}"    "http://localhost:${TOKENIZATION_ISSUER_API_PORT:-4120}"
printf "  %-26s %-34s %s\n" "Tokenization · Market"  "http://localhost:${TOKENIZATION_MARKETPLACE_WEB_PORT:-8101}" "http://localhost:${TOKENIZATION_MARKETPLACE_API_PORT:-4121}"
printf "  %-26s %-34s %s\n" "Tokenization · Admin"   "http://localhost:${TOKENIZATION_ADMIN_WEB_PORT:-8102}"     "http://localhost:${TOKENIZATION_ADMIN_API_PORT:-4122}"
echo
echo -e "  ${Y}Neither API publishes a host port.${N} The six edges above are the only way in."
echo "  Prove it:   node scripts/personas-e2e.mjs"
echo "  Stop it:    docker compose -f docker-compose.personas.yml down"
echo
