#!/usr/bin/env bash
# Bring up one stack, or both.
#
#   bash scripts/stack-up.sh identity                  # identity alone
#   bash scripts/stack-up.sh tokenization              # tokenization alone
#   bash scripts/stack-up.sh identity tokenization     # both, linked
#
# Each stack is a separate compose project on a shared external network, so they
# can be started in either order, stopped independently, and run on different
# hosts with only the network to change.
#
# THE LINK IS ONE-WAY AND OPTIONAL. Tokenization asks identity whether a subject
# holds a credential; identity never calls tokenization. Naming both stacks here
# is what mints the peer key and wires that seam — start tokenization alone and
# it simply runs without it.
set -euo pipefail
cd "$(dirname "$0")/.."

C="\033[1;36m"; G="\033[1;32m"; Y="\033[1;33m"; R="\033[1;31m"; N="\033[0m"
say() { echo -e "${C}[stack]${N} $*"; }
die() { echo -e "${R}[stack] ERROR:${N} $*" >&2; exit 1; }

ENV_FILE=".env.personas"
NETWORK="xi-net"
ID_COMPOSE="docker compose -p xi-identity -f docker-compose.identity.yml"
TOK_COMPOSE="docker compose -p xi-tokenization -f docker-compose.tokenization.yml"

WANT_IDENTITY=0; WANT_TOKENIZATION=0
for arg in "$@"; do
  case "$arg" in
    identity) WANT_IDENTITY=1;;
    tokenization) WANT_TOKENIZATION=1;;
    *) die "unknown stack '$arg' — expected 'identity' and/or 'tokenization'";;
  esac
done
[ $# -gt 0 ] || die "name at least one stack: identity, tokenization, or both"

command -v docker >/dev/null || die "docker is not on PATH"

# ── Secrets, once, and kept ──────────────────────────────────────────────────
# DID_MASTER_KEY must never be regenerated for a deployment that already has
# data: every custodial seed is encrypted under it, and a new one orphans them
# all — surfacing later as "Unsupported state or unable to authenticate data".
if [ ! -f "$ENV_FILE" ]; then
  say "minting $ENV_FILE (first run)"
  {
    echo "# Generated by scripts/stack-up.sh — git-ignored, keep it."
    echo "JWT_SECRET=$(openssl rand -hex 32)"
    echo "DID_MASTER_KEY=$(openssl rand -hex 32)"
  } > "$ENV_FILE"
fi
# Repo .env FIRST (ledger settings), the deployment's own file LAST so its
# secrets win — see the long note this replaces in personas-up.sh.
if [ -f .env ]; then set -a; . ./.env; set +a; fi
set -a; . "./$ENV_FILE"; set +a

docker network inspect "$NETWORK" >/dev/null 2>&1 || {
  say "creating the shared network '$NETWORK'"
  docker network create "$NETWORK" >/dev/null
}

wait_for() {   # wait_for <port> <label>
  local port="$1" label="$2" code
  for i in $(seq 1 150); do
    code=$(curl -so /dev/null -w '%{http_code}' "http://localhost:${port}/api/v1/config" 2>/dev/null || echo 000)
    case "$code" in 200|401) return 0;; esac
    [ "$i" = 150 ] && die "$label never answered through :$port (last status $code)"
    sleep 2
  done
}

# ── Identity ─────────────────────────────────────────────────────────────────
if [ "$WANT_IDENTITY" = 1 ]; then
  say "building and starting the IDENTITY stack…"
  $ID_COMPOSE up -d --build
  # Through the edge to a REAL route: nginx answers its own /healthz whether or
  # not anything is behind it.
  wait_for "${IDENTITY_ISSUER_API_PORT:-4110}" "identity"
  say "identity is up ✓"
fi

# ── The peer key, only when BOTH are wanted ──────────────────────────────────
if [ "$WANT_IDENTITY" = 1 ] && [ "$WANT_TOKENIZATION" = 1 ]; then
  if grep -q '^IDENTITY_SERVICE_KEY=' "$ENV_FILE" 2>/dev/null; then
    say "peer key already present in $ENV_FILE"
  else
    say "minting the identity:assert peer key through the issuer edge…"
    KEY=$(IDENTITY_URL="http://localhost:${IDENTITY_ISSUER_API_PORT:-4110}/api/v1" node scripts/mint-identity-peer-key.mjs) \
      || die "could not mint the peer key"
    [ -n "$KEY" ] || die "the peer key came back empty"
    echo "IDENTITY_SERVICE_KEY=$KEY" >> "$ENV_FILE"
  fi
  set -a; . "./$ENV_FILE"; set +a
  export IDENTITY_SERVICE_URL="${IDENTITY_SERVICE_URL:-http://identity-api:4000/api/v1}"
  say "tokenization will delegate identity to identity-api over '$NETWORK'"
elif [ "$WANT_TOKENIZATION" = 1 ]; then
  # STANDALONE. Both variables must be empty together: half a pair is the
  # configuration that boots and then fails on the first gated transfer.
  export IDENTITY_SERVICE_URL=""
  export IDENTITY_SERVICE_KEY=""
  say "tokenization will run STANDALONE (no identity service)"
fi

# ── Tokenization ─────────────────────────────────────────────────────────────
if [ "$WANT_TOKENIZATION" = 1 ]; then
  say "building and starting the TOKENIZATION stack…"
  $TOK_COMPOSE up -d --build
  wait_for "${TOKENIZATION_ISSUER_API_PORT:-4120}" "tokenization"
  say "tokenization is up ✓"
fi

echo
echo -e "${G}✅ STACK(S) UP${N}"
echo
printf "  %-26s %-34s %s\n" "APP" "WEB" "ITS API EDGE"
printf "  %-26s %-34s %s\n" "───" "───" "────────────"
if [ "$WANT_IDENTITY" = 1 ]; then
printf "  %-26s %-34s %s\n" "Identity · Issuer"     "http://localhost:${IDENTITY_ISSUER_WEB_PORT:-8090}"   "http://localhost:${IDENTITY_ISSUER_API_PORT:-4110}"
printf "  %-26s %-34s %s\n" "Identity · Verifier"   "http://localhost:${IDENTITY_VERIFIER_WEB_PORT:-8091}" "http://localhost:${IDENTITY_VERIFIER_API_PORT:-4111}"
printf "  %-26s %-34s %s\n" "Identity · Wallet"     "http://localhost:${IDENTITY_HOLDER_WEB_PORT:-8092}"   "http://localhost:${IDENTITY_HOLDER_API_PORT:-4112}"
fi
if [ "$WANT_TOKENIZATION" = 1 ]; then
printf "  %-26s %-34s %s\n" "Tokenization · Issuer" "http://localhost:${TOKENIZATION_ISSUER_WEB_PORT:-8100}"      "http://localhost:${TOKENIZATION_ISSUER_API_PORT:-4120}"
printf "  %-26s %-34s %s\n" "Tokenization · Market" "http://localhost:${TOKENIZATION_MARKETPLACE_WEB_PORT:-8101}" "http://localhost:${TOKENIZATION_MARKETPLACE_API_PORT:-4121}"
printf "  %-26s %-34s %s\n" "Tokenization · Admin"  "http://localhost:${TOKENIZATION_ADMIN_WEB_PORT:-8102}"       "http://localhost:${TOKENIZATION_ADMIN_API_PORT:-4122}"
fi
echo
echo -e "  ${Y}Neither API publishes a host port.${N} The edges above are the only way in."
echo "  Stop one:   docker compose -p xi-identity -f docker-compose.identity.yml down"
echo "              docker compose -p xi-tokenization -f docker-compose.tokenization.yml down"
echo
