#!/usr/bin/env bash
# ============================================================
# TokenLayer — 5-Node Hyperledger Besu IBFT 2.0 Network
# Usage: ./besu-network/start-network.sh
# Requirements: Docker, docker compose, Node.js (with ethers in backend/node_modules)
# ============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║   TokenLayer · 5-Node Hyperledger Besu IBFT 2.0 Setup   ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# ── Step 1: Derive node1 enode public key ─────────────────────────────
echo "[ 1/5 ] Deriving node1 enode public key..."
PRIVKEY=$(cat "$SCRIPT_DIR/node1/key")

# Use ethers from the backend's node_modules (always available in this project)
PUBKEY=$(node -e "
const {Wallet} = require('$PROJECT_ROOT/backend/node_modules/ethers');
const w = new Wallet('0x$PRIVKEY');
// Uncompressed public key minus the '04' prefix = 128 hex chars
console.log(w.signingKey.publicKey.slice(4));
" 2>/dev/null || echo "")

if [ -z "$PUBKEY" ] || [ ${#PUBKEY} -ne 128 ]; then
  echo "  ERROR: Could not derive node1 public key."
  echo "         Make sure backend dependencies are installed: cd backend && npm install"
  exit 1
fi

NODE1_ENODE="enode://${PUBKEY}@besu-node-1:30303"
echo "  ✓ Node1 enode: ${PUBKEY:0:20}...@besu-node-1:30303"

# ── Step 2: Write .env for docker-compose variable substitution ───────
echo "[ 2/5 ] Writing .env file..."
cat > "$PROJECT_ROOT/.env" <<EOF
# Auto-generated by besu-network/start-network.sh — do not edit manually
BESU_NODE1_ENODE=${NODE1_ENODE}
EOF
echo "  ✓ Written: $PROJECT_ROOT/.env"

# ── Step 3: Start node1 (bootnode + RPC) ─────────────────────────────
echo "[ 3/5 ] Starting besu-node-1 (bootnode + RPC)..."
cd "$PROJECT_ROOT"
docker compose up -d besu-node-1

echo -n "  Waiting for node1 to be healthy"
TIMEOUT=120
ELAPSED=0
until docker inspect --format='{{.State.Health.Status}}' besu-node-1 2>/dev/null | grep -q "healthy"; do
  if [ $ELAPSED -ge $TIMEOUT ]; then
    echo ""
    echo "  ERROR: node1 did not become healthy within ${TIMEOUT}s."
    echo "         Check logs: docker compose logs besu-node-1"
    exit 1
  fi
  sleep 3
  printf "."
  ELAPSED=$((ELAPSED + 3))
done
echo " ✓"

# ── Step 4: Start nodes 2-5 ───────────────────────────────────────────
echo "[ 4/5 ] Starting besu-node-2 through besu-node-5..."
docker compose up -d besu-node-2 besu-node-3 besu-node-4 besu-node-5
echo "  Waiting 20s for peer discovery and consensus formation..."
sleep 20

# ── Step 5: Verify network health ────────────────────────────────────
echo "[ 5/5 ] Verifying network..."

PEER_COUNT=$(curl -sf -X POST \
  -H "Content-Type: application/json" \
  --data '{"jsonrpc":"2.0","method":"net_peerCount","params":[],"id":1}' \
  http://localhost:8545 \
  | python3 -c "import sys,json; print(int(json.load(sys.stdin)['result'],16))" 2>/dev/null || echo "0")

BLOCK_NUMBER=$(curl -sf -X POST \
  -H "Content-Type: application/json" \
  --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' \
  http://localhost:8545 \
  | python3 -c "import sys,json; print(int(json.load(sys.stdin)['result'],16))" 2>/dev/null || echo "0")

VALIDATORS=$(curl -sf -X POST \
  -H "Content-Type: application/json" \
  --data '{"jsonrpc":"2.0","method":"ibft_getValidatorsByBlockNumber","params":["latest"],"id":1}' \
  http://localhost:8545 \
  | python3 -c "import sys,json; v=json.load(sys.stdin).get('result',[]); print(len(v))" 2>/dev/null || echo "0")

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║                  Network Status                         ║"
echo "╠══════════════════════════════════════════════════════════╣"
printf "║  RPC Endpoint   : %-38s ║\n" "http://localhost:8545"
printf "║  WS  Endpoint   : %-38s ║\n" "ws://localhost:8546"
printf "║  Connected Peers: %-38s ║\n" "$PEER_COUNT / 4 expected"
printf "║  Current Block  : %-38s ║\n" "$BLOCK_NUMBER"
printf "║  IBFT Validators: %-38s ║\n" "$VALIDATORS / 5 expected"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

if [ "$PEER_COUNT" -lt 3 ]; then
  echo "⚠  WARNING: Fewer than 3 peers connected."
  echo "   The network needs ≥ 4 of 5 nodes to reach IBFT consensus."
  echo "   Check logs: docker compose logs -f besu-node-1"
else
  echo "✓  Network is healthy and producing blocks!"
fi

echo ""
echo "Useful commands:"
echo "  View logs:      docker compose logs -f besu-node-1"
echo "  Stop network:   docker compose stop besu-node-1 besu-node-2 besu-node-3 besu-node-4 besu-node-5"
echo "  Deploy contracts: cd blockchain && BESU_PRIVATE_KEY=0x8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63 npx hardhat run scripts/deploy.ts --network besu"
echo ""
